name: Update Jadwal JSON

on:
  workflow_dispatch:
  repository_dispatch:
    types: [update-jadwal]

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch latest data
        run: |
          curl -o jadwal.json ${{ secrets.DATA_URL }}

      - name: Commit and Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add jadwal.json
          git commit -m "Update jadwal.json [CI]" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/SpaceAx/XI-B.git HEAD:main
